### ISSUE TITLE
Issue with session timeout

### ISSUE THREAD

**Issue by guptavivek** [developerforce/SalesforceDurablePushTopicDemo#4]
Is there any way to avoid user logging out due to inactivity and keep listen and process the events in a VM?

**Comment by jthurst01** [comment]
You can set up an external listener outside of Salesforce in the VM of your choice.  There is a sample connector that can be used - https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/code_sample_java_client_intro.htm

This git sample is focused more on a demo for a user actively working in the UI.

**Comment by guptavivek** [comment]
Yes i came across EMP-Connector before but was looking for a way to have it implemented in Salesforce due to time constraint for delivery of this app. Thanks for your help!
